# pull official base image
FROM python:3.8.6-slim-buster

# create directory for the app user
RUN mkdir -p /home/app

# create the app user
RUN addgroup --system app && adduser --system --group app

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ENVIRONMENT prod
ENV TESTING 0

# install system dependencies
RUN apt-get update \
    && apt-get -y install sqlite3 libsqlite3-dev netcat gcc postgresql \
    && apt-get clean

# install python dependencies
RUN pip install --upgrade pip
RUN pip install poetry
RUN pip install "uvicorn[standard]==0.13.1"
COPY ./pyproject.toml .
COPY ./poetry.lock .
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# add app
COPY . .

# change to the app user
USER app

# run gunicorn
CMD gunicorn --bind 0.0.0.0:$PORT app.main:app -k uvicorn.workers.UvicornWorker
